// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wpqthkvidfmjyroaijiq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndwcXRoa3ZpZGZtanlyb2FpamlxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI5NTk2MzQsImV4cCI6MjA2ODUzNTYzNH0.3HdTw587IUP-Y-QR59qMuijAzlqk9ifiZq_bP14hcjc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});